---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secrets
data:
  POSTGRES_USER: dXNlcgo=
  POSTGRES_PASSWORD: cGFzc3dvcmQK
  POSTGRES_DB: dXNlcnNkYgo=

---
apiVersion: v1
kind: Secret
metadata:
  name: books-db-secrets
data:
  POSTGRES_USER: dXNlcgo=
  POSTGRES_PASSWORD: cGFzc3dvcmQK
  POSTGRES_DB: Ym9va3NkYgo=

  
