---
apiVersion: v1
kind: Service
metadata:
  name: booksdb-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    db: books
  ports:
    - port: 5432
      targetPort: 5432
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booksdb
spec:
  selector:
    matchLabels:
      db: books
  serviceName: booksdb-svc
  replicas: 2
  template:
    metadata:
      labels:
        db: books
    spec:
      containers:
      - name: booksdb
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
          - name: POSTGRES_USER
            value: user
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: booksdb
        resources:
            requests:
              memory: 64M
              cpu: 200m
            limits:
              memory: 128M
              cpu: 500m
        volumeMounts:
        - name: books-pvc
          mountPath: /usr/share/nginx/html
          subpath: 
  volumeClaimTemplates:
  - metadata:
      name: books-pvc
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: managed
      resources:
        requests:
          storage: 1Gi


