---
apiVersion: v1
kind: Service
metadata:
  name: booksdb-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    db: books
  ports:
    - port: 5432
      targetPort: 5432
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booksdb
spec:
  selector:
    matchLabels:
      db: books
  serviceName: booksdb-svc
  replicas: 1
  template:
    metadata:
      labels:
        db: books
    spec:
      containers:
      - name: booksdb
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
          - secretRef: books-db-secrets
        resources:
            requests:
              memory: 100Mi
              cpu: 200m
            limits:
              memory: 250Mi
              cpu: 250m
        volumeMounts:
        - name: books-pvc
          mountPath: /var/lib/postgres/data
          subpath: data
  volumeClaimTemplates:
  - metadata:
      name: books-pvc
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: managed
      resources:
        requests:
          storage: 1Gi


