---
apiVersion: v1
kind: Service
metadata:
  name: usersdb-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    db: users
  ports:
    - port: 5432
      targetPort: 5432
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: usersdb
spec:
  selector:
    matchLabels:
      db: users
  serviceName: usersdb-svc
  replicas: 1
  template:
    metadata:
      labels:
        db: users
    spec:
      containers:
      - name: usersdb
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
          - secretRef:
              name: users-db-secrets
        resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 250Mi
              cpu: 250m
        volumeMounts:
        - name: user-pvc
          mountPath: /var/lib/postgres/data
          subpath: data
  volumeClaimTemplates:
  - metadata:
      name: user-pvc
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi


